[package]
name = "snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
itertools = "0.10.3"
iyes_loopless = "0.4.0"
rand = "0.8.5"
kayak_ui = { git = "https://github.com/StarArawn/kayak_ui", rev = "2e8c374943dc7be4f7febc95ae2a3d273ad90038", features = [
    "bevy_renderer",
] }
bevy_asset_loader = { version = "0.10.0", features = ["2d"] }

[features]
