[package]
name = "bevy-snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
bevy_kira_audio = "0.9.0"
# bevy_ninepatch = "0.6.0"
itertools = "0.10.3"
iyes_loopless = "0.4.0"
rand = "0.8.5"
tracing = "0.1.33"
kayak_ui = { git = "https://github.com/christopherbiscardi/kayak_ui", rev = "91656eff2b815cbaf3690cc47e087a2b6dce90a2", features = [
    "bevy_renderer",
] }
