[package]
name = "snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
itertools = "0.10.3"
iyes_loopless = "0.5.1"
rand = "0.8.5"
