[package]
name = "snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9"
itertools = "0.10.3"
iyes_loopless = "0.9"
rand = "0.8.5"
bevy_asset_loader = { version = "0.14", features = ["2d"] }
bevy_kira_audio = "0.13.0"
kayak_ui = "0.2.0"

[features]
