[package]
name = "bevy-snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7.0", features = [
    "animation",
    "bevy_gilrs",
    "bevy_winit",
    "render",
    "png",
    "hdr",
    "x11",
    "filesystem_watcher",
] }
bevy_kira_audio = "0.9.0"
# bevy_ninepatch = "0.6.0"
itertools = "0.10.3"
iyes_loopless = "0.4.0"
rand = "0.8.5"
tracing = "0.1.33"
kayak_ui = { git = "https://github.com/StarArawn/kayak_ui", rev = "0e9008dd204421b79035526ccafa1af296a51143", features = [
    "bevy_renderer",
] }
bevy_asset_loader = { version = "0.10.0", features = ["2d"] }
